const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Autogenerated API Documentation',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['./api/v1/routes/*.js'],
};

const specs = swaggerJsdoc(options);

module.exports = app=>{
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));

}
